env:
  browser: true
  es6: true
  node: true

plugins:
  - react

extends: 
  - 'eslint:recommended'
  - plugin:react/recommended

parserOptions:
  sourceType: module

rules:
  indent:
    - error
    - 2
  max-len:
    - error
    - ignoreComments: true
    - code: 120
  no-console: off
  linebreak-style:
    - error
    - unix
  no-empty: warn
  quotes:
    - error
    - single
  semi:
    - error
    - always
  react/jsx-uses-react:
    - error
  react/jsx-uses-vars:
    - error

